### ISSUE TITLE
Example Datasets + homology tutorial

### ISSUE THREAD

**Issue by lordgrilo** [jg-you/scm#1]
This is pretty neat! 
I think we should also add:
- [x] the datasets we used for the paper, for reproducibility purposes 
- [ ] a short tutorial on how to compute the homology from the output, possibly using one-two different libraries, e.g. Holes (hence javaplex) and Perseus/Phat. I can do that if you want.

**Comment by jg-you** [comment]
@lordgrilo : cancelling the homology tutorial?
